#version 430 core
#include "common/uniforms.glsl"       // Camera, Time, LUTs
#include "metrics/kerr_full.glsl" // Metric-specific physics (orbitRK4)
// #include "metrics/schwarzschild_full.glsl" // Metric-specific physics (orbitRK4)
// #include "metrics/schwarzschild_reduced.glsl" // Metric-specific physics (orbitRK4)
#include "common/scene.glsl"          // Particles, Disk, Skybox
#include "common/march_full.glsl"  // The actual main() loop for 2D solvers
// #include "common/march_reduced.glsl"  // The actual main() loop for 2D solvers